### ISSUE TITLE
Road to 100% coverage

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/system-image-node-module#4]
There's still some uncovered lines, that needs to change ;)

https://coveralls.io/github/ubports/system-image-node-module?branch=master

**Comment by gsilvapt** [comment]
One of the methods which lacks tests the most is `createInitialCommands` in `client.js`. It is not very clear what should happen in case any of the `if` fails. Consider the following example:

```
  createInstallCommands(files, installerCheck, wipe, enable) {
    var cmd = startCommands;
    if (wipe === true) cmd += "\nformat data";
[...]
```
If `wipe === false`, what should happen? For the time being, it seems to be recording a different set of commands and that might be the intended action. The same goes for other `if` statements in that method. How can we find a way to review these so I can try creating some tests for the lines?

**Comment by NeoTheThird** [comment]
@gsilvapt The [if-statement](https://github.com/ubports/system-image-node-module/blob/master/src/client.js#L79) just adds the command to clear the internal storage to the command list, if wipe is specified in the call. It might be more clear if we turned that into a shorthand-assignment. Feel free to send a PR for that, if you fell it could be useful for new people working with the code. We also don't actually *need* the deep comparison for wipe, it's unlikely any one will call it with something else than a boolean, so that could be more efficient.

**Comment by gsilvapt** [comment]
I did not altered the code when creating some test scenarios. I experienced with it a bit to see what it returned in which case. If it's not that relevant, I guess we can keep it as it is. The code readability is fine, just wanted to ensure we do not want special behaviors for these validations. I was able to create some test scenarios to cover the lines coveralls mention that were not covered.

However, we should discuss how we will approach some methods. Here are my thoughts, all for `client.js`:
* The createInstallCommandsFile, the first if is mostly related with IO commands and third-party packages. I am not sure how we can test or rather if we should. That would mean we had to create a test for something already tested. I'd leave it as it is, although this might mean we do not reach 100%.
* If the `getDeviceIndex` is private, then we might not be able to test it. I'm accostumed to Java, so I'm not sure even how private methods work in Node :joy: But, usually we cannot test private methods. Not sure how it works in Node;
* What is heavily damaging the coverage of this file, are two methods in the end of the file, `getFileBasenameArray` and `getFilePathArray`. These have comments above asking if we still need this, which is also related with issue #3 . Perhaps we should resolve #3 before continuing with this issue? (Although we should really try to do TDD from hereon! :laughing: )

**Comment by NeoTheThird** [comment]
Those issues would not actually be defined as private, but imported as a local module that just doesn't exported outside. Kind of like [common.js](https://github.com/ubports/system-image-node-module/blob/master/src/common.js). But I still need @mariogrip's feedback if he thinks this is a good idea. Imho it would allow for some more elegant black-boxing of this module.

Testing is still possible in that case, you can just create a new unit-test that just imports that module from its source file and tests it. The clean way would actually be to do that for common.js as well ;) Unit-tests should test units, if you test  a unit in its implementation, you have an integration test

**Comment by gsilvapt** [comment]
> Testing is still possible in that case, you can just create a new unit-test that just imports that module from its source file and tests it. The clean way would actually be to do that for common.js as well ;) Unit-tests should test units, if you test a unit in its implementation, you have an integration test

So you're saying we should add tests to ensure, for instance, `createInstallCommandsFile` method can create a directory called `commandFile` if it does not already exist and perform the remaining commands as expected?  Just that the bit that takes care of this is only `fs` module.
